config/routes.rb
require 'resque_web'

RodeoRails4::Application.routes.draw do

  scope '/twilio', as: 'twilio' do
    post '/sms',    to: 'twilio#sms'
    post '/voice',  to: 'twilio#voice'
  end

  #error routes
  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'
  get '/401', :to => 'errors#unauthorized'

  devise_for :users

  scope '/admin' do
    get '/', to: 'admin#landing'

    scope '/users/:id/' do
      get '/passwords/edit' => 'users#edit_password', as: 'admin_edit_password'
      patch '/passwords/update' => 'users#update_password', as: 'admin_update_password'
    end

    resources :users

    resources :events do
      post '/clone' => 'events#clone'
      post '/import' => 'events#import', as: 'admin_events_import'
      post '/upload' => 'events#upload'
      resources :users, :controller => 'event_users', :as => 'users', :only => [:index, :edit, :update]
    end

    resque_web_constraint = lambda do |request|
      current_user = request.env['warden'].user
      current_user.present? && current_user.has_role?(:admin)
    end

    constraints resque_web_constraint do
      mount ResqueWeb::Engine => "/resque_web"
      # mount RailsAdmin::Engine => '/rails'
    end
  end

  root :to => 'welcome#index'
end

RodeoRails4::Application.routes.draw do

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  scope '/:event_slug' do
    get '/' => 'event_public#landing', as: 'event_landing'
    get '/facts' => 'event_public#facts_show'

    scope 'leaderboard', as: 'leaderboard' do
      get '/' => 'event_public#leaderboard'
      get '/categories/:id' => 'leaderboard#category', as: 'category'
      get '/teams/:id' => 'leaderboard#team', as: 'team'

      scope 'api', as: 'api', :defaults => {:format => 'json'} do
        get '/event' => 'leaderboard#event_leaderboard', as: 'event'
        get '/unlimited' => 'leaderboard#unlimited_leaderboard', as: 'unlimited'
      end

    end

    get '/leaderboard_at_capture' => 'leaderboard#leaderboard_at_capture'
    get '/get_empty_leaderboard_html' => 'leaderboard#get_empty_leaderboard_html'

    get '/participants/summary/:participant_id' => 'participants#summary'

    scope '/teams' do
      get '/' => 'teams#teams'
      get '/registration' => 'teams#registration'
      post '/registration' => 'teams#registration_create'
      get '/:team_slug' => 'teams#leaderboard'
      get '/:team_slug/confirmation' => 'teams#captain_edit_confirmation', as: 'captain_edit_confirmation_dos'
      get '/:team_slug/:token' => 'teams#captain_edit'
      patch '/:team_slug/:token' => 'teams#captain_edit_commit', as: 'captain_edit'
    end

    scope '/admin' do
      get '/' => 'events#admin'

      scope :reports, as: 'reports' do
        get '/results' => 'event_reports#results'
        get '/categories' => 'event_reports#show_categories'
        get '/team_categories' => 'event_reports#team_categories'
      end

      scope 'sms' do
        get '/' => 'events_sms#index', as: 'sms'
        put '/send_standings' => 'events_sms#send_standings_sms', as: 'sms_send_standings'
        put '/send_custom' => 'events_sms#send_custom_sms', as: 'sms_send_custom'
      end

      resources :captures

      get '/teams/team_lookup', to: 'teams#team_lookup'

      resources :teams do
        member do
          get 'badges', defaults: { format: 'pdf' }
        end

        collection do
          get '/check_badge_status', to: 'teams#check_badge_status'
        end

        get '/check_in' => 'teams#check_in'
        get '/check_out' => 'teams#check_out'
      end

      resources :categories do
        resources :category_items
      end

      resources :super_categories do
        get '/categories' => 'super_categories#categories_index'
      end

      resources :premium_category_groupings

      resources :event_scale_openings

      resources :participants do
        member do
          get 'badge', defaults: { format: 'pdf'}
        end

        get '/get_info', action: :get_info, on: :collection
      end

      resources :participations, except: [:new, :create, :edit, :update, :destroy] do
        get :autocomplete_participation_capture, on: :collection
        get :autocomplete_participation_form, on: :collection
        get '/get_info', action: :get_info, on: :collection
      end

    end
  end
end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id                         :integer          not null, primary key
#  first_name                 :string(256)      not null
#  last_name                  :string(256)      not null
#  street                     :string(256)
#  city                       :string(256)
#  zipcode                    :string(25)
#  email                      :string(256)
#  home_phone                 :string(25)
#  mobile_phone               :string(25)
#  updated_at                 :datetime         not null
#  created_at                 :datetime         not null
#  temporary                  :boolean          default(FALSE)
#  does_receive_notifications :boolean          default(FALSE), not null
#  gender_id                  :integer          not null
#  shirt_size_id              :integer
#  date_of_birth              :date
#  name_vector_index_col      :tsvector
#

class Participant < ActiveRecord::Base
  nilify_blanks
  resourcify
  has_paper_trail

  require 'geocoder'

  has_one :user
  belongs_to :gender
  belongs_to :shirt_size
  belongs_to :mobile_carrier

  has_many :captures, dependent: :destroy
  has_many :participations

  has_many :teams, :through => :participations
  has_many :events, :through => :participations
  has_many :event_participation_types, :through => :participations
  has_many :participation_types, :through => :event_participation_types

  validates_presence_of :first_name, :last_name, :does_receive_notifications, :gender
  validates_datetime :date_of_birth,
                     after: lambda { Chronic.parse('1900-01-01') },
                     after_message: 'must be after Jan 1, 1900',
                     before: :today,
                     before_message: 'must be not be after today'

  before_save :check_change
  after_save :update_vector_column

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def address
    s = Geocoder.search(self.zipcode)[0]

    "#{self.street}, #{self.city}, #{s.nil? ? "" : s.state} #{self.zipcode}" unless self.street.nil? && self.city.nil? && self.zipcode.nil?
  end

  def participation(object)
    if object.is_a? Event
      self.participations.where(event: object).first

    else if object.is_a? Team
           self.participations.where(team: object).first
         end
    end
  end

  def qr_code(size, event)
    # TODO make this an attachment

    data = Hash.new
    data[:event_url] = "/#{event.slug}/participants/get_info"
    data[:participant_id] = self.id

    "https://chart.googleapis.com/chart?cht=qr&chld=M|0&chs=#{size}x#{size}&chl=#{CGI.escape(data.to_json)}"
  end

  def self.spreadsheet_header
    [
        'Team',
        'First Name',
        'Last Name',
        'Street',
        'City',
        'Zip',
        'Email',
        'Home Phone',
        'Mobile Phone',
        'Gender',
        'Shirt Size'
    ]
  end

  def spreadsheet_row(event)
    attrs = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}.except(:created_at, :updated_at, :id, :temporary, :does_receive_notifications, :gender_id, :shirt_size_id, :mobile_carrier_id, :date_of_birth, :name_vector_index_col).values
    [self.participation(event).try(:team).try(:name)] + attrs + [self.gender.try(:name), self.shirt_size.try(:abbreviation)]
  end

  private

  def check_change
    #we only want to do the rest of the code if we have changed
    return unless self.changed.include?('first_name') || self.changed.include?('last_name')
    self.participations.reject {|t| t.event.is_over}.each{|part| BadgeGenerationJob.perform_later(part)}
  end

  def update_vector_column
    Participant.connection.execute("UPDATE participants SET name_vector_index_col = to_tsvector('english', coalesce(first_name,'') || ' ' || coalesce(last_name,'')) WHERE id = #{self.id}")
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  include EventSluggable

  before_action :get_participant, only: [:show, :edit, :update, :destroy, :badge, :get_info]

  include ActionAuthorizable

  # GET /participants
  # GET /participants.json
  # GET /participants.xlsx
  def index
    @participants = Participant
                        .joins({:participations => [:team, { :event_participation_type => :participation_type }]}, :gender)
                        .where( participations: {event_id: @event.id} )
                        .order(%w(participants.last_name participants.first_name))
                        .select([
                                    'participants.*',
                                    'teams.number AS team_number',
                                    'teams.name as team_name',
                                    'teams.checked_in as team_checked_in',
                                    'genders.name as gender_name',
                                    'participation_types.name as participation_type'
                                ])
  end

  # GET /participants/1
  def show
  end

  def get_info

  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
    @team = @participant.participation(@event).team
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        @team = Team.where(:id => params[:team_id]).first
        @team.participants << @participant
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update

    result = false
    Participant.transaction do

      @participant.update_attributes(participant_params)

      participation = @participant.participation(@event)
      participation.event_participation_type = EventParticipationType.find(params[:event_participation_type_id])

      participation.save!

      result = true
    end

    respond_to do |format|
      if result
        format.html { redirect_to participants_path(event_slug: @event.slug), notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy

    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
      format.js
    end
  end

  #leaderboard page for a participant
  def summary
    @participant = Participant.find(params[:participant_id])
    @category_place = Hash.new()

    @event.super_categories.each do |s_cat|
      data = Hash.new

      s_cat.each do |category|
        data[category.id] = category.caps({:participant_id => params[:participant_id]})
      end

      @category_place[s_cat.name] = data

    end
    render :layout => 'plain'
  end

  ##### front facing routes

  def badge
    relative_part = @participant.participation(@event)

    if relative_part.pending_jobs.count > 0
      redirect_to participants_path(event_slug: @event.slug, id: @participant.id), notice: 'There are badges that have not been generated yet'
      return
    end

    respond_to do |format|
      format.pdf{
        badges = relative_part.badge
        send_file badges.path, :filename => "#{@participant.last_name} Badges.pdf"
      }
    end

  end

  private

  def get_participant
    @participant = @event.participants.where(id: params[:id]).first
    if @participant.nil?
      raise 'Participant not found.'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def participant_params
    params.require(:event_participation_type_id)
    params.require(:participant).permit(:age, :city, :email, :first_name, :participant_number ,:home_phone, :last_name, :gender, :does_receive_notifications, :participation_type, :mobile_carrier, :mobile_phone, :shirt_size, :street, :zipcode, :shirt_size_id, :date_of_birth, :gender_id)
  end

end

app/views/participants/_form.html.erb
<%= form_tag "/#{@event.slug}/admin/participants", :method => :post, :remote => true do %>

 <%= render 'part' %>

    <div class="row">
      <div class="col-md-2">
        <%= submit_tag "Submit", class: 'form-control' %>
      </div>
    </div>

<% end %>

app/views/participants/_part.html.erb
<%= fields_for @participant do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% @participant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field col-md-3">
      <%= f.label :first_name %>
      <br/>
      <%= f.text_field :first_name, :class => 'validate[required] form-control' %>
    </div>
    <div class="field col-md-3">
      <%= f.label :last_name %>
      <br/>
      <%= f.text_field :last_name, :class => 'validate[required] form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="field col-md-3">
      <%= f.label :street %>
      <br/>
      <%= f.text_field :street, class:  'form-control'  %>
    </div>
    <div class="field col-md-3">
      <%= f.label :city  %>
      <br/>
      <%= f.text_field :city, class:  'form-control'  %>
    </div>
    <div class="field col-md-3">
      <%= f.label :zipcode %>
      <br/>
      <%= f.text_field :zipcode, class:  'form-control'  %>
    </div>
  </div>

  <div class="row">
    <div class="field col-md-3">
      <%= f.label :email  %>
      <br/>
      <%= f.text_field :email, :class => 'validate[custom[email]] form-control' %>
    </div>
    <div class="field col-md-3">
      <%= f.label :home_phone %>
      <br/>
      <%= f.text_field :home_phone, :class => 'phone validate[custom[phone]] form-control' %>
    </div>
    <div class="field col-md-3">
      <%= f.label :mobile_phone %>
      <br/>
      <%= f.text_field :mobile_phone, :class => 'validate[condRequired[mobile_carrier]] form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="field col-md-2">
      <%= f.label :shirt_size %>
      <br/>
      <%= f.select :shirt_size_id, options_for_select(ShirtSize.all.map{ |t| [t.abbreviation, t.id]}, @participant.shirt_size_id), {:include_blank => 'n/a'}, class: 'form-control' %>
    </div>
    <div class="field col-md-2">
      <%= f.label :gender %>
      <br/>
      <%= f.select :gender_id, options_for_select(Gender.all.map{ |t| [t.name, t.id]}, @participant.gender_id), {:include_blank => '--SELECT--'}, {:class => 'validate[required] form-control'} %>
    </div>

    <div class="field col-md-2">
      <%= label_tag :participation_type %>
      <br/>
      <%= select_tag :event_participation_type_id, options_for_select(@event.event_participation_types.map{ |t| [t.participation_type.name, t.id]}, @participant.participation(@event).event_participation_type.id), {:class => 'validate[required] form-control'} %>
    </div>
  </div>
    
<% end %>

<br>
<br>

app/views/participants/create.js.erb
window.location = "<%= participant_path(:event_slug => @event.slug, :id => @participant.id).html_safe %>"

app/views/participants/edit.html.erb
<h3>Edit: <%= "#{@participant.first_name} #{@participant.last_name}" %> </h3>
<%= form_tag "/#{@event.slug}/admin/participants/#{@participant.id}", :method => :put, :remote => true do %>

  <%= render 'part' %>
    <div class="row">
      <div class="col-md-2">
        <%= submit_tag "Submit", class: 'form-control' %>
      </div>
    </div>
<% end %>


<%= javascript_include_tag 'participants' %>

app/views/participants/index.html.erb
<h1>Participants</h1>

<table class="table table-striped" id="participantTable">
  <thead>
  <tr>
    <th>#</th>
    <th>Last name</th>
    <th>First name</th>
    <th>Team</th>
    <th>Gender</th>
    <!--<th>Email</th>-->
    <!--<th>Home phone</th>-->
    <!--<th>Mobile phone</th>-->
    <th>Type</th>
    <th></th>
    <th></th>
    <th><i class="fa fa-check"></i> In</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @participants.each_with_index do |participant, index| %>
  <tr>
    <td><%= (index+1).to_s %></td>
    <td><%= participant.last_name %></td>
    <td><%= participant.first_name %></td>
    <td><%= participant.team_name + (participant.team_number.nil? ? '' : " (##{participant['team_number'].to_s})") %></td>
    <td><%= participant.gender_name || 'n/a' %></td>
    <td><%= participant.participation_type %></td>
    <td><% if can? :show, participant %><%= link_to '<i class="fa fa-folder-open"></i>'.html_safe, participant_path(:event_slug => @event.slug, :id => participant.id) %><% end %></td>
    <td><% if can? :edit, participant %><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_participant_path(:event_slug => @event.slug, :id => participant.id) %><% end %></td>
    <td><%= '<i class="fa fa-check"></i>'.html_safe if participant.team_checked_in %></td>
    <td><%= link_to 'Print Badges', badge_participant_path(:event_slug => @event.slug, :id => participant.id), class: "form-control btn btn-default print-button" %></td>
  </tr>
<% end %>
  </tbody>
</table>
<script>
    $('#participantTable').DataTable();
</script>

app/views/participants/new.html.erb
<h3>New participant</h3>

<%= render 'form' %>

<%= javascript_include_tag 'participants' %>

app/views/participants/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @participant.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @participant.last_name %>
</p>

<p>
  <b>Participant Number:</b>
  <%= @participant.participation(@event).number %>
</p>

<p>
  <b>Gender:</b>
  <% if @participant.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.gender.name %>
  <% end %>
</p>

<p>
  <b>Street:</b>
  <% if @participant.street.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.street %>
  <% end %>
</p>

<p>
  <b>City:</b>
  <% if @participant.city.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.city %>
  <% end %>
</p>

<p>
  <b>Zipcode:</b>
  <% if @participant.zipcode.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.zipcode %>
  <% end %>
</p>

<p>
  <b>Email:</b>
  <% if @participant.email.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.email %>
  <% end %>
</p>

<p>
  <b>Home phone:</b>
  <% if @participant.home_phone.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.home_phone %>
  <% end %>
</p>

<p>
  <b>Mobile phone:</b>
  <% if @participant.mobile_phone.nil? %>
      <text style="color:#808080">n/a</text>
  <% else %>
      <%= @participant.mobile_phone %>
  <% end %>
</p>

<p>
  <b>Mobile carrier:</b>
  <% if !@participant.mobile_carrier.nil? %>
      <%= @participant.mobile_carrier.name %>
  <% else %>
      <text style="color:#808080">n/a</text>
  <% end %>
</p>

<p>
  <b>Shirt size:</b>
  <% if !@participant.shirt_size.nil? %>
      <%= @participant.shirt_size.name %>
  <% else %>
      <text style="color:#808080">n/a</text>
  <% end %>
</p>

<p>
  <b>Type:</b>
  <%= @participant.participation(@event).event_participation_type.participation_type.name %>
</p>

<div class="id-card section_to_print">

  <div class="id-card-event-header">
    <h3 class="text-center"><%= @event.name %></h3>
    <h4 class="text-center"><%= @event.start_date.strftime("%b %d, %Y") %>
      - <%= @event.end_date.strftime("%b %d, %Y") %></h4>
  </div>

  <img src="/assets/logo2.png" class="logo-image"/>
  <table class="id-info">
    <tbody>
    <tr>
      <td style="text-align: right">ID:</td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td style="text-align: left"><%= @participant.participation(@event).number %></td>
    </tr>
    <tr>
      <td style="text-align: right;">Name:</td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td style="text-align: left"><%= @participant.first_name %> <%= @participant.last_name %></td>
    </tr>
    <tr>
      <td style="text-align: right">Team:</td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td style="text-align: left"><%= @participant.participation(@event).team.name %></td>
    </tr>
    <tr>
      <td style="text-align: right">Type:</td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td style="text-align: left"><%= @participant.participation(@event).event_participation_type.participation_type.name %></td>
    </tr>
    <tr>
      <td style="text-align: right">Leaderboard:</td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td style="text-align: left"><%= @event.short_leaderboard_url %></td>
    </tr>
    <tr>
      <td style="text-align: right">Team Summary:</td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td style="text-align: left"><%= @participant.participation(@event).team.summary_short_url %></td>
    </tr>
    </tbody>
  </table>

  <%= image_tag @participant.qr_code(200, @event), :class => 'qr-code' %>

</div>
<br>
<%= link_to 'Edit', edit_participant_path(:event_slug => @event.slug, :id => @participant.id), :class => 'btn btn-default' %>
<%= link_to 'Back', :back, :class => 'btn btn-default' %>

app/views/participants/summary.html.erb
<div class="leaderboard-body">
  <div class="event-title-container">
    <h2 class="text-center"><%= "Captures for " + @participant.name%></h2>
  </div>

  <div id="leaderboard-categories">
    <% @category_place.each do |name,s_category|%>
      <% if s_category.count > 0 %>
        <h4 class="text-center"><%= name %></h4>
        <% s_category.each do |name,category| %>
          <% if category.count > 0 %>

            <div class="leaderboard-category">
              <h4 class="text-center"><%= name %></h4>

              <table class="table table-striped">
                <tbody>
                <% category.each do|place| %>
                  <tr>
                    <%#= raise place.inspect %>
                    <!-- For when we add species stuff to the caps method in category -->
                    <td><%#= place['species'] %></td>
                    <td><%= place['weight'] %></td>
                    <td><%= place['total_points'].present? ? "#{place['total_points'].to_i} pts." : place['row'].to_i.ordinalize %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/participants/update.js.erb
window.location = "<%= participants_path(event_slug: @event.slug) %>";