config/routes.rb
require 'resque_web'

RodeoRails4::Application.routes.draw do

  scope '/twilio', as: 'twilio' do
    post '/sms',    to: 'twilio#sms'
    post '/voice',  to: 'twilio#voice'
  end

  #error routes
  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'
  get '/401', :to => 'errors#unauthorized'

  devise_for :users

  scope '/admin' do
    get '/', to: 'admin#landing'

    scope '/users/:id/' do
      get '/passwords/edit' => 'users#edit_password', as: 'admin_edit_password'
      patch '/passwords/update' => 'users#update_password', as: 'admin_update_password'
    end

    resources :users

    resources :events do
      post '/clone' => 'events#clone'
      post '/import' => 'events#import', as: 'admin_events_import'
      post '/upload' => 'events#upload'
      resources :users, :controller => 'event_users', :as => 'users', :only => [:index, :edit, :update]
    end

    resque_web_constraint = lambda do |request|
      current_user = request.env['warden'].user
      current_user.present? && current_user.has_role?(:admin)
    end

    constraints resque_web_constraint do
      mount ResqueWeb::Engine => "/resque_web"
      # mount RailsAdmin::Engine => '/rails'
    end
  end

  root :to => 'welcome#index'
end

RodeoRails4::Application.routes.draw do

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  scope '/:event_slug' do
    get '/' => 'event_public#landing', as: 'event_landing'
    get '/facts' => 'event_public#facts_show'

    scope 'leaderboard', as: 'leaderboard' do
      get '/' => 'event_public#leaderboard'
      get '/categories/:id' => 'leaderboard#category', as: 'category'
      get '/teams/:id' => 'leaderboard#team', as: 'team'

      scope 'api', as: 'api', :defaults => {:format => 'json'} do
        get '/event' => 'leaderboard#event_leaderboard', as: 'event'
        get '/unlimited' => 'leaderboard#unlimited_leaderboard', as: 'unlimited'
      end

    end

    get '/leaderboard_at_capture' => 'leaderboard#leaderboard_at_capture'
    get '/get_empty_leaderboard_html' => 'leaderboard#get_empty_leaderboard_html'

    get '/participants/summary/:participant_id' => 'participants#summary'

    scope '/teams' do
      get '/' => 'teams#teams'
      get '/registration' => 'teams#registration'
      post '/registration' => 'teams#registration_create'
      get '/:team_slug' => 'teams#leaderboard'
      get '/:team_slug/confirmation' => 'teams#captain_edit_confirmation', as: 'captain_edit_confirmation_dos'
      get '/:team_slug/:token' => 'teams#captain_edit'
      patch '/:team_slug/:token' => 'teams#captain_edit_commit', as: 'captain_edit'
    end

    scope '/admin' do
      get '/' => 'events#admin'

      scope :reports, as: 'reports' do
        get '/results' => 'event_reports#results'
        get '/categories' => 'event_reports#show_categories'
        get '/team_categories' => 'event_reports#team_categories'
      end

      scope 'sms' do
        get '/' => 'events_sms#index', as: 'sms'
        put '/send_standings' => 'events_sms#send_standings_sms', as: 'sms_send_standings'
        put '/send_custom' => 'events_sms#send_custom_sms', as: 'sms_send_custom'
      end

      resources :captures

      get '/teams/team_lookup', to: 'teams#team_lookup'

      resources :teams do
        member do
          get 'badges', defaults: { format: 'pdf' }
        end

        collection do
          get '/check_badge_status', to: 'teams#check_badge_status'
        end

        get '/check_in' => 'teams#check_in'
        get '/check_out' => 'teams#check_out'
      end

      resources :categories do
        resources :category_items
      end

      resources :super_categories do
        get '/categories' => 'super_categories#categories_index'
      end

      resources :premium_category_groupings

      resources :event_scale_openings

      resources :participants do
        member do
          get 'badge', defaults: { format: 'pdf'}
        end

        get '/get_info', action: :get_info, on: :collection
      end

      resources :participations, except: [:new, :create, :edit, :update, :destroy] do
        get :autocomplete_participation_capture, on: :collection
        get :autocomplete_participation_form, on: :collection
        get '/get_info', action: :get_info, on: :collection
      end

    end
  end
end

app/models/premium_category_grouping.rb
# == Schema Information
#
# Table name: premium_category_groupings
#
#  id         :integer          not null, primary key
#  name       :text             not null
#  price      :float            default(0.0)
#  event_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PremiumCategoryGrouping < ActiveRecord::Base
  has_many :categories, dependent: :nullify
  belongs_to :event

  has_many :team_premium_category_groupings, dependent: :destroy
  has_many :teams, through: :team_premium_category_groupings

  validates_uniqueness_of :name, scope: [:event_id]
  validates_presence_of :name
  validates_presence_of :event_id
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/premium_category_groupings_controller.rb
class PremiumCategoryGroupingsController < ApplicationController
  include EventSluggable

  before_action :authenticate_user!
  before_action :set_premium_category_grouping, only: [:show, :edit, :update, :destroy]

  include ActionAuthorizable

  # GET /premium_category_groupings
  # GET /premium_category_groupings.json
  def index
    @premium_category_groupings = PremiumCategoryGrouping.where(event: @event)
  end

  # GET /premium_category_groupings/1
  # GET /premium_category_groupings/1.json
  def show
  end

  # GET /premium_category_groupings/new
  def new
    @premium_category_grouping = PremiumCategoryGrouping.new
  end

  # GET /premium_category_groupings/1/edit
  def edit
  end

  # POST /premium_category_groupings
  # POST /premium_category_groupings.json
  def create
    @premium_category_grouping = PremiumCategoryGrouping.new(premium_category_grouping_params)

    respond_to do |format|
      if @premium_category_grouping.save
        format.html { redirect_to premium_category_groupings_path(@event.slug), notice: 'Premium category grouping was successfully created.' }
        format.json { render action: 'show', status: :created, location: @premium_category_grouping }
      else
        format.html { render action: 'new' }
        format.json { render json: @premium_category_grouping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /premium_category_groupings/1
  # PATCH/PUT /premium_category_groupings/1.json
  def update
    respond_to do |format|
      if @premium_category_grouping.update(premium_category_grouping_params)
        format.html { redirect_to premium_category_groupings_path(@event.slug), notice: 'Premium category grouping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @premium_category_grouping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /premium_category_groupings/1
  # DELETE /premium_category_groupings/1.json
  def destroy
    @premium_category_grouping.destroy
    respond_to do |format|
      format.html { redirect_to premium_category_groupings_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_premium_category_grouping
    @premium_category_grouping = PremiumCategoryGrouping.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def premium_category_grouping_params
    params.require(:premium_category_grouping).permit(:name, :price, :event_id)
  end

end

app/helpers/premium_category_groupings_helper.rb
module PremiumCategoryGroupingsHelper
  def format_premium_grouping_name(grouping)
    grouping.price > 0 ? "#{grouping.name} (#{number_to_currency(grouping.price)})" : grouping.name
  end
end

app/views/premium_category_groupings/_form.html.haml
= form_for @premium_category_grouping do |f|
  - if @premium_category_grouping.errors.any?
    #error_explanation
      %h2= "#{pluralize(@premium_category_grouping.errors.count, "error")} prohibited this premium_category_grouping from being saved:"
      %ul
        - @premium_category_grouping.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: 'Name'
    = f.hidden_field :event_id, value: @event.id

  .form-group
    = f.label :price
    .input-group
      .input-group-addon $
      = f.text_field :price, class: 'form-control', placeholder: 'Price'

  .actions
    = f.submit 'Save', class: 'btn btn-default'

app/views/premium_category_groupings/edit.html.haml
%h1 Editing Premium Category Grouping

= render 'form'

app/views/premium_category_groupings/index.html.haml
%h1 Premium Category Groupings

%table.table.display
  %thead
    %tr
      %th Name
      %th Price
      %th Actions

  %tbody
    - @premium_category_groupings.each do |premium_category_grouping|
      %tr
        %td= premium_category_grouping.name
        %td= number_to_currency(premium_category_grouping.price)
        %td
          - if can? :edit, premium_category_grouping
            = link_to '<i class="fa fa-pencil"> Edit</i>'.html_safe, edit_premium_category_grouping_path(@event.slug,premium_category_grouping) if can?(:edit, premium_category_grouping)
          - if can? :delete, premium_category_grouping
            = link_to '<i class="fa fa-trash"> Delete</i>'.html_safe, premium_category_grouping_path(@event.slug, premium_category_grouping), :method => :delete, :data => { :confirm => 'Are you sure?' } if can?(:destroy, premium_category_grouping)

  %br

- if can? :create, PremiumCategoryGrouping
  = link_to 'New Premium category grouping', new_premium_category_grouping_path(@event.slug), class: 'btn btn-default'

app/views/premium_category_groupings/new.html.haml
%h1 New Premium Category Grouping

= render 'form'

app/views/premium_category_groupings/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_premium_category_grouping_path(@premium_category_grouping)
\|
= link_to 'Back', premium_category_groupings_path