config/routes.rb
require 'resque_web'

RodeoRails4::Application.routes.draw do

  scope '/twilio', as: 'twilio' do
    post '/sms',    to: 'twilio#sms'
    post '/voice',  to: 'twilio#voice'
  end

  #error routes
  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'
  get '/401', :to => 'errors#unauthorized'

  devise_for :users

  scope '/admin' do
    get '/', to: 'admin#landing'

    scope '/users/:id/' do
      get '/passwords/edit' => 'users#edit_password', as: 'admin_edit_password'
      patch '/passwords/update' => 'users#update_password', as: 'admin_update_password'
    end

    resources :users

    resources :events do
      post '/clone' => 'events#clone'
      post '/import' => 'events#import', as: 'admin_events_import'
      post '/upload' => 'events#upload'
      resources :users, :controller => 'event_users', :as => 'users', :only => [:index, :edit, :update]
    end

    resque_web_constraint = lambda do |request|
      current_user = request.env['warden'].user
      current_user.present? && current_user.has_role?(:admin)
    end

    constraints resque_web_constraint do
      mount ResqueWeb::Engine => "/resque_web"
      # mount RailsAdmin::Engine => '/rails'
    end
  end

  root :to => 'welcome#index'
end

RodeoRails4::Application.routes.draw do

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  scope '/:event_slug' do
    get '/' => 'event_public#landing', as: 'event_landing'
    get '/facts' => 'event_public#facts_show'

    scope 'leaderboard', as: 'leaderboard' do
      get '/' => 'event_public#leaderboard'
      get '/categories/:id' => 'leaderboard#category', as: 'category'
      get '/teams/:id' => 'leaderboard#team', as: 'team'

      scope 'api', as: 'api', :defaults => {:format => 'json'} do
        get '/event' => 'leaderboard#event_leaderboard', as: 'event'
        get '/unlimited' => 'leaderboard#unlimited_leaderboard', as: 'unlimited'
      end

    end

    get '/leaderboard_at_capture' => 'leaderboard#leaderboard_at_capture'
    get '/get_empty_leaderboard_html' => 'leaderboard#get_empty_leaderboard_html'

    get '/participants/summary/:participant_id' => 'participants#summary'

    scope '/teams' do
      get '/' => 'teams#teams'
      get '/registration' => 'teams#registration'
      post '/registration' => 'teams#registration_create'
      get '/:team_slug' => 'teams#leaderboard'
      get '/:team_slug/confirmation' => 'teams#captain_edit_confirmation', as: 'captain_edit_confirmation_dos'
      get '/:team_slug/:token' => 'teams#captain_edit'
      patch '/:team_slug/:token' => 'teams#captain_edit_commit', as: 'captain_edit'
    end

    scope '/admin' do
      get '/' => 'events#admin'

      scope :reports, as: 'reports' do
        get '/results' => 'event_reports#results'
        get '/categories' => 'event_reports#show_categories'
        get '/team_categories' => 'event_reports#team_categories'
      end

      scope 'sms' do
        get '/' => 'events_sms#index', as: 'sms'
        put '/send_standings' => 'events_sms#send_standings_sms', as: 'sms_send_standings'
        put '/send_custom' => 'events_sms#send_custom_sms', as: 'sms_send_custom'
      end

      resources :captures

      get '/teams/team_lookup', to: 'teams#team_lookup'

      resources :teams do
        member do
          get 'badges', defaults: { format: 'pdf' }
        end

        collection do
          get '/check_badge_status', to: 'teams#check_badge_status'
        end

        get '/check_in' => 'teams#check_in'
        get '/check_out' => 'teams#check_out'
      end

      resources :categories do
        resources :category_items
      end

      resources :super_categories do
        get '/categories' => 'super_categories#categories_index'
      end

      resources :premium_category_groupings

      resources :event_scale_openings

      resources :participants do
        member do
          get 'badge', defaults: { format: 'pdf'}
        end

        get '/get_info', action: :get_info, on: :collection
      end

      resources :participations, except: [:new, :create, :edit, :update, :destroy] do
        get :autocomplete_participation_capture, on: :collection
        get :autocomplete_participation_form, on: :collection
        get '/get_info', action: :get_info, on: :collection
      end

    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include EventSluggable

  before_filter :get_category, :only => [:edit, :update, :destroy, :show]

  include ActionAuthorizable

  def index
    @categories = @event.categories.joins(:super_category).order('super_categories.page ASC, super_categories.position ASC, super_categories.name ASC, super_categories.id ASC, categories.grouping_number ASC, categories.position ASC, categories.name ASC, categories.id ASC')
    respond_to do |format|
      format.html
      format.json { render json: @categories }
    end
  end

  def show
    @category = Category.where(:id => params[:id]).first
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def edit
    @category = Category.where(:id => params[:id]).first
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def create
    params = copy_sources_and_orders(category_params)
    super_category = SuperCategory.where(:id => params[:super_category_id]).first

    @category = Category.new(params.except(:items))
    @error = false
    begin
      Category.transaction do
        @category.save!
        super_category.categories << @category
        @category.super_category = super_category
        # If there are items, add them to the category's items
        if params[:items]
          params[:items].each do |item|
            @item = Categoryitem.create!(item)
            @category.categoryitems << @item
          end
        end
      end
    rescue Exception => e
      @error = true
    end

    respond_to do |format|
      if !@error
        flash_success('Category successfully created.',false)
        format.html { redirect_to category_path(:event_slug => @event.slug, :id => @category.id) }
        format.json { render json: @category, status: :created, location: @category }
      else
        flash_object_errors(@category,nil,'created')
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.where(:id => params[:id]).first
    @category.destroy!
    flash_success('Category successfully deleted.')
    respond_to do |format|
      format.html { redirect_to categories_path(:event_slug => @event.slug) }
      format.json { render json: @category }
    end
  end

  def update
    params = copy_sources_and_orders(category_params)
    respond_to do |format|
      if @category.update_attributes(params)
        flash_success('Category successfully updated.')
        format.html { render action: "show"}
        format.json { head :no_content }
      else
        flash_object_errors(@category,nil,'updated')
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def get_category
    @category = @event.categories.where(:id => params[:id]).first
    if @category.nil?
      raise ActionController::RoutingError.new('Category not found.')
    end
  end

  # Helper method to set blank selects to nil
  def copy_sources_and_orders(category_params)
    if category_params[:score_2_source].blank?
      category_params[:score_2_source] = nil
    end
    if category_params[:score_2_order].blank?
      category_params[:score_2_order] = nil
    end
    if category_params[:score_3_source].blank?
      category_params[:score_3_source] = nil
    end
    if category_params[:score_3_order].blank?
      category_params[:score_3_order] = nil
    end

    # If there is no source or order, the is_random boolean should be null instead of false
    if category_params[:score_2_source].nil? && category_params[:score_2_order].nil? && category_params[:score_2_is_random] == '0'
      category_params[:score_2_is_random] = nil
    end
    # If there is no source or order, the random boolean should be null instead of false
    if category_params[:score_3_source].nil? && category_params[:score_3_order].nil? && category_params[:score_3_is_random]== '0'
      category_params[:score_3_is_random] = nil
    end
    return category_params
  end

  def category_params
    params.require(:category).permit(:start_age, :end_age, :positions, :name, :subtitle, :super_category_id, :score_entity, :score_grouping, :score_grouping_limit, :category_type, :has_distinct_places, :valid_start_time, :valid_end_time, :gender_id, :premium_category_grouping_id, :score_1_source, :score_1_order, :score_2_source, :score_2_order, :score_2_is_random, :score_3_source, :score_3_order, :score_3_is_random, :display_mode, :position, :grouping_number, :category_background_color,:category_text_color)
  end

end

app/views/categories/_form.html.erb
<%= fields_for @category do |f| %>

    <div class="card">

      <div class="body">

        <div class="row">

          <div class="field col-md-6">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, :required => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-6">
            <%= f.label :subtitle, 'Subtitle' %>
            <%= f.text_field :subtitle, :required => false, :class => 'form-control' %>
          </div>

          <div class="field col-md-3">
            <%= f.label :super_category_id, 'Super Category' %>
            <%= f.select :super_category_id, SuperCategory.where(:event_id => Event.where(:slug => params[:event_slug])).collect { |sc| [sc.name, sc.id] }, :class => 'form-control' %>
          </div>

          <div class="field col-md-3">
            <%= f.label :positions, 'Number of Positions' %>
            <%= f.select :positions, options_for_select((1..20).step(1), @category.positions), { :include_blank => true, :class => 'form-control' }, { :required => true } %>
          </div>

          <div class="field col-md-3">
            <%= f.label :start_age, 'Start Age' %>
            <%= f.select :start_age, options_for_select((5..100).step(1), @category.start_age), :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-3">
            <%= f.label :end_age, 'End Age' %>
            <%= f.select :end_age, options_for_select((5..100).step(1), @category.end_age), :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-3">
            <%= f.label :valid_start_time, 'Start Time' %>
            <div class="date-wrapper">
              <div class="date-wrapper">
                <%= f.text_field :valid_start_time, :class => 'datetime-input form-control' %>
                <%= f.hidden_field :valid_start_time, :class => 'datetime-input date-value form-control' %>
              </div>
            </div>
          </div>

          <div class="field col-md-3">
            <%= f.label :valid_end_time, 'End Time' %>
            <div class="date-wrapper">
                <%= f.text_field :valid_end_time, :class => 'datetime-input form-control' %>
                <%= f.hidden_field :valid_end_time, :class => 'datetime-input date-value form-control' %>
            </div>
          </div>

          <div class="field col-md-3">
            <%= f.label :score_entity, 'Score Entity' %>
            <%= f.select :score_entity, Category::SCORE_ENTITY.invert, { :include_blank => true, :class => 'form-control'} , { :required => true } %>
          </div>

          <div class="field col-md-3">
            <%= f.label :category_type, 'Category Type' %>
            <%= f.select :category_type, Category::CATEGORY_TYPE.invert, { :include_blank => true, :class => 'form-control' }, { :required => true } %>
          </div>

          <div class="field col-md-3">
            <%= f.label :score_grouping, 'Score Grouping' %>
            <%= f.select :score_grouping, Category::SCORE_GROUPING.invert, { :include_blank => true, :class => 'form-control' }, { :required => true } %>
          </div>

          <div class="field col-md-3">
            <%= f.label :score_grouping_limit, 'Score Grouping Limit' %>
            <%= f.select :score_grouping_limit, options_for_select((1..20).step(1), @category.score_grouping_limit), { :include_blank => true, :class => 'form-control' } %>
          </div>

          <div class="field col-md-3">
            <%= f.label :display_mode, 'Display Mode' %>
            <%= f.select :display_mode, Category::DISPLAY_MODE.invert, { :include_blank => true, :class => 'form-control' }, { :required => true } %>
          </div>

          <div class="field col-md-3">
            <%= f.label :has_distinct_places, 'Has Distinct Places' %>
            <%= f.check_box :has_distinct_places, :class => 'form-control' %>
          </div>

          <div class="field col-md-3">
            <%= f.label :premium_category_grouping_id, 'Premium Category Grouping' %>
            <%= f.select :premium_category_grouping_id, PremiumCategoryGrouping.where(:event => @event).order('name asc').collect { |sc| [sc.name, sc.id] }, :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-3">
            <%= f.label :gender_id, 'Gender' %>
            <%= f.select :gender_id, { Gender.all.first.name => Gender.all.first.id, Gender.all.second.name => Gender.all.second.id }, :include_blank => true, :class => 'form-control' %>
          </div>

        </div>

        <div class="row">

          <div class="field col-md-4">
            <%= f.label :score_1_source, 'Score 1 Source' %>
            <%= f.select :score_1_source, Category::SCORE_SOURCE.invert, { :include_blank => true, :class => 'form-control' }, { :required => true } %>
          </div>

          <div class="field col-md-4">
            <%= f.label :score_1_order, 'Score 1 Order' %>
            <%= f.select :score_1_order, Category::SCORE_ORDER.invert, { :include_blank => true, :class => 'form-control' }, { :required => true } %>
          </div>
        </div>

        <div class="row">

          <div class="field col-md-4">
            <%= f.label :score_2_source, 'Score 2 Source' %>
            <%= f.select :score_2_source, Category::SCORE_SOURCE.invert, :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-4">
            <%= f.label :score_2_order, 'Score 2 Order' %>
            <%= f.select :score_2_order, Category::SCORE_ORDER.invert, :include_blank => true, :class => 'form-control' %>
          </div>


          <div class="field col-md-2">
            <%= f.label :score_2_is_random, 'Decided Randomly?' %>
            <%= f.check_box :score_2_is_random, :class => 'form-control' %>
          </div>
      </div>

      <div class="row">
          <div class="field col-md-4">
            <%= f.label :score_3_source, 'Score 3 Source' %>
            <%= f.select :score_3_source, Category::SCORE_SOURCE.invert, :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-4">
            <%= f.label :score_3_order, 'Score 3 Order' %>
            <%= f.select :score_3_order, Category::SCORE_ORDER.invert, :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-2">
            <%= f.label :score_3_is_random, 'Decided Randomly?' %>
            <%= f.check_box :score_3_is_random, :class => 'form-control' %>
          </div>
      </div>

        <div class="row">

          <div class="field col-md-4">
            <%= f.label :grouping_number, 'Group Number' %>
            <%= f.select :grouping_number, options_for_select((1..20).step(1), @category.grouping_number), :include_blank => true, :class => 'form-control' %>
          </div>

          <div class="field col-md-4">
            <%= f.label :position, 'Position In Group' %>
            <%= f.select :position, options_for_select((0..20).step(1), @category.position), {:include_blank => true, :class => 'form-control'}, { :required => true } %>
          </div>

        </div>

        <div class="row">
          <div class="col-md-6">

            <div class="row">
              <div class="col-md-6">
                <%= f.label :category_text_color %> <br>
              </div>
            </div>

            <div class="row color-fields">
              <div class="col-md-6">
                <%= color_field_tag :category_text_color,  f.object.category_text_color.try(:upcase), :class => 'form-control color-picker' %>
              </div>
              <div class="col-md-6">
                <%= f.text_field :category_text_color, value: f.object.category_text_color.try(:upcase) , :class =>'form-control color-field'%>
              </div>
            </div>

          </div>

          <div class="col-md-6">

            <div class="row">
              <div class="col-md-6">
                <%= f.label :category_background_color %> <br>
              </div>
            </div>

            <div class="row color-fields">
              <div class="col-md-6">
                <%= color_field_tag :category_background_color,  f.object.category_background_color.try(:upcase), :class => 'form-control color-picker' %>
              </div>
              <div class="col-md-6">
                <%= f.text_field :category_background_color, value: f.object.category_background_color.try(:upcase) , :class =>'form-control color-field'%>
              </div>
            </div>

          </div>

        </div>

      </div>

    </div>

<% end %>

app/views/categories/_summary_box.html.erb
<h4><%= category.name %></h4>

<%
   ph = '<span class="empty-value">n/a</span>'.html_safe
   def make_text_preview(category)
     text = (category.category_text_color || 'Inherited') + ' on ' + (category.category_background_color || 'Inherited')
     return '<span style="margin:5px; margin-left:0px; padding:5px 20px; text-align:center; font-weight:bold; color:' + category.get_text_color + '; background-color:' + category.get_background_color + ';">' + text + '</span>'
    end
%>

<div class="category-information">
  <table id="event_categories">
    <tr>
      <td style="width:33%;">ID</td>
      <td class="value"><%= category.id.nil? ? ph : category.id.to_s.titleize %></td>
    </tr>
    <tr>
      <td>Subtitle</td>
      <td class="value"><%= category.subtitle.nil? ? ph : category.subtitle %></td>
    </tr>
    <tr>
      <td>Grouping</td>
      <td class="value"><%= "Grouping Number #{category.grouping_number} / Position #{category.position}" %></td>
    </tr>
    <tr>
      <td>Gender</td>
      <td class="value"><%= category.gender.nil? ? ph : category.gender.name %></td>
    </tr>
    <tr>
      <td>Start Age</td>
      <td class="value"><%= category.start_age.nil? ? ph : category.start_age %></td>
    </tr>
    <tr>
      <td>End Age</td>
      <td class="value"><%= category.end_age.nil? ? ph : category.end_age %></td>
    </tr>
    <tr>
      <td>Positions</td>
      <td class="value"><%= category.positions.nil? ? ph : category.positions %></td>
    </tr>
    <tr>
      <td>Premium Category Grouping</td>
      <td class="value"><%= category.premium_category_grouping.try(:name) %></td>
    </tr>
    <tr>
      <td>Start Time</td>
      <td class="value"><%= category.valid_start_time.nil? ? nil : category.valid_start_time.in_time_zone(category.super_category.event.timezone).to_s %></td>
    </tr>
    <tr>
      <td>End Time</td>
      <td class="value"><%= category.valid_end_time.nil? ? nil : category.valid_end_time.in_time_zone(category.super_category.event.timezone).to_s %></td>
    </tr>
    <tr>
      <td>Score Entity</td>
      <td class="value"><%= category.score_entity.nil? ? ph : category.score_entity.to_s.titleize %></td>
    </tr>
    <tr>
      <td>Distinct Places</td>
      <td class="value"><%= category.has_distinct_places.nil? ? ph : category.has_distinct_places ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <td>Source 1</td>
      <td class="value"><%= category.score_1_source.nil? ? ph : category.score_1_source.to_s.titleize + ', ' + category.score_1_order.to_s.titleize %></td>
    </tr>
    <tr>
      <td>Source 2</td>
      <td class="value"><%= category.score_2_source.nil? ? ph : category.score_2_source.to_s.titleize + ', ' + category.score_2_order.to_s.titleize + (category.score_2_is_random ? ' (Decided Randomly)' : '') %></td>
    </tr>
    <tr>
      <td>Source 3</td>
      <td class="value"><%= category.score_3_source.nil? ? ph : category.score_3_source.to_s.titleize + ', ' + category.score_3_order.to_s.titleize + (category.score_3_is_random ? ' (Decided Randomly)' : '') %></td>
    </tr>
    <tr>
      <td>Display Mode</td>
      <td class="value"><%= category.display_mode.to_s.titleize %></td>
    </tr>
    <tr>
      <%
         gr = category.score_grouping.nil? ? ph : category.score_grouping.to_s.titleize
         if (category.score_grouping.to_s == 'top_n')
           gr = gr + " (#{category.score_grouping_limit})"
         end
      %>
      <td>Score Grouping</td>
      <td class="value"><%= gr %></td>
    </tr>
    <tr>
      <td>Type</td>
      <td class="value"><%= category.category_type.nil? ? ph : category.category_type.to_s.titleize %></td>
    </tr>
    <% if category.category_type.to_s == 'species_unit' %>
    <tr>
      <td>Species Unit</td>
      <td class="value"><%= category.category_species_unit_items.first.nil? ? ph : category.category_species_unit_items.first.unit.description %></td>
    </tr>
    <% end %>
    <tr>
      <td>Items</td>
      <%
         items = {}
         if category.category_type.to_s == 'species_unit'
           category.category_species_unit_items.each do |item|
             items[item.species.name] = nil
           end

        elsif category.category_type.to_s == 'species_capture'
         category.category_species_capture_items.each do |item|
           items[item.species.name] = nil
         end

         elsif category.category_type.to_s == 'species_points'
           category.category_species_points_items.each do |item|
             items[item.species.name] = item.points.to_s + ' Points'
           end

         elsif category.category_type.to_s == 'group'
           category.category_grouping_items.order('place ASC').each do |item|
             inner = []
             item.category_grouping_item_super_categories.each do |cat|
               inner << cat.super_category.name + ' (' + cat.super_category.id.to_s + ')'
             end
             items[('Place ' + item.place.to_s + ' &rarr; ' + item.points.to_s + ' Points').html_safe] = inner
           end
           puts items.to_s
         else
           raise 'Unknown category type.'
         end
         if items.length == 0
           items = nil
         end
      %>
      <td class="value">
        <% if items.nil? %>
            <!-- It's Empty -->
            <%= ph %>
        <% else %>
            <ul style="list-style-type:square">
              <% items.each do |k, v| %>
                  <li><%= k.to_s %></li>
                  <% if v.kind_of?(Array) %>
                    <%= v.join(', ') %>
                  <% else %>
                      <% if v != nil %>
                          &rarr;
                          <%= v.to_s %>
                      <% end %>
                  <% end %>

              <% end %>
            </ul>
        <% end %>

      </td>
    </tr>

    <tr>
      <td>Generated Description</td>
      <td class="value"><%= category.get_description %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td class="value"><%= category.description || ph%></td>
    </tr>
    <tr>
      <td>Additional Description</td>
      <td class="value"><%= category.additional_description || ph%></td>
    </tr>
    <tr>
      <td>Colors</td>
      <td class="value"><%= make_text_preview(category).html_safe %></td>
    </tr>
  </table>
</div>

app/views/categories/edit.html.erb
<%= form_tag "/#{@category.super_category.event.slug}/admin/categories/#{@category.id}", :method => :patch do %>
    <%= render 'form' %>
    <%= submit_tag "Submit" %>
<% end %>

app/views/categories/index.html.erb
<style type="text/css">
  .super-category-row td {
    text-align:center;
    font-weight:bold;
    color:white;
  }
</style>

<% super_category = nil %>

<h1>Categories</h1>
<table class="table table-striped">
  <% @categories.each do |category| %>
      <% if super_category != category.super_category.id %>
        <tr class="super-category-row">
            <td colspan="5" style="background-color:<%= category.super_category.get_background_color %>; color:<%= category.super_category.get_text_color %>;"><%= category.super_category.name %></td>
        </tr>
        <% super_category = category.super_category.id %>
      <% end %>
      <tr>
        <td><%= category.grouping_number.to_s + '.' + category.position.to_s %></td>
        <td>
          <%= category.name %>
          <% if !category.subtitle.nil? %>
            <span style="color:gray;"> (<%= category.subtitle %>)</span>
          <% end %>
        </td>
        <td><%= category.premium_category_grouping.nil? ? '' : category.premium_category_grouping.name %></td>
        <td><% if can? :show, category %><%= link_to '<i class="fa fa-folder-open"></i>'.html_safe, category_path(:event_slug => @event.slug, :id => category.id) %><% end %></td>
        <td><% if can? :edit, category %><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_category_path(:event_slug => @event.slug, :id => category.id) %><% end %></td>
      </tr>
  <% end %>
</table>

<% if can? :create, Category %>
    <%= link_to 'New Category', new_category_path(:event_slug => @event.slug), :class=>'btn btn-default' %>
<% end %>

app/views/categories/leaderboard.html.erb
<script type="text/javascript">
    var LB_OPTIONS = {
        teamID : null,
        mode : Leaderboard.constants.STATIC,
        rankingsURL : "<%= escape_javascript(leaderboard_api_unlimited_path(:event_slug => @event.slug)).html_safe %>",
        websocketSubscription : 'event_<%= @event.id.to_s %>_unlimited_leaderboard'
    };
</script>
<%= render :partial => '/leaderboard/leaderboard_page', :locals => {:event => @category.super_category.event, :team => nil, :categories => [@category], :make_category_links => false, :include_descriptions => false} %>

app/views/categories/new.html.erb
<%= form_tag "/#{@event.slug}/admin/categories", :method => :post do %>
    <%= render 'form' %>
    <%= submit_tag "Submit" %>
<% end %>

app/views/categories/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<p>
  <b>Super Category:</b>
  <%= SuperCategory.where(:id => @category.super_category_id).first.name %>
</p>

<%= render :partial => 'summary_box', :locals => {:category => @category} %>

<br/>

<% if can? :edit, @category %><%= link_to 'Edit', edit_category_path(:event_slug => @event.slug, :id => @category.id), :class=>'btn btn-default' %><% end %>
<% if can? :destroy, @category %><%= link_to 'Delete', category_path(:event_slug => @event.slug, :category_id => @category.id), :confirm => "Delete this category?", :method => :delete, :class=>'btn btn-default' %><% end %>
<%= link_to 'Show Items', category_category_items_path(:event_slug => @event.slug, :category_id => @category.id), :class=>'btn btn-default' %>
<%= link_to 'Back', :back, :class=>'btn btn-default' %>