config/routes.rb
require 'resque_web'

RodeoRails4::Application.routes.draw do

  scope '/twilio', as: 'twilio' do
    post '/sms',    to: 'twilio#sms'
    post '/voice',  to: 'twilio#voice'
  end

  #error routes
  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'
  get '/401', :to => 'errors#unauthorized'

  devise_for :users

  scope '/admin' do
    get '/', to: 'admin#landing'

    scope '/users/:id/' do
      get '/passwords/edit' => 'users#edit_password', as: 'admin_edit_password'
      patch '/passwords/update' => 'users#update_password', as: 'admin_update_password'
    end

    resources :users

    resources :events do
      post '/clone' => 'events#clone'
      post '/import' => 'events#import', as: 'admin_events_import'
      post '/upload' => 'events#upload'
      resources :users, :controller => 'event_users', :as => 'users', :only => [:index, :edit, :update]
    end

    resque_web_constraint = lambda do |request|
      current_user = request.env['warden'].user
      current_user.present? && current_user.has_role?(:admin)
    end

    constraints resque_web_constraint do
      mount ResqueWeb::Engine => "/resque_web"
      # mount RailsAdmin::Engine => '/rails'
    end
  end

  root :to => 'welcome#index'
end

RodeoRails4::Application.routes.draw do

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  scope '/:event_slug' do
    get '/' => 'event_public#landing', as: 'event_landing'
    get '/facts' => 'event_public#facts_show'

    scope 'leaderboard', as: 'leaderboard' do
      get '/' => 'event_public#leaderboard'
      get '/categories/:id' => 'leaderboard#category', as: 'category'
      get '/teams/:id' => 'leaderboard#team', as: 'team'

      scope 'api', as: 'api', :defaults => {:format => 'json'} do
        get '/event' => 'leaderboard#event_leaderboard', as: 'event'
        get '/unlimited' => 'leaderboard#unlimited_leaderboard', as: 'unlimited'
      end

    end

    get '/leaderboard_at_capture' => 'leaderboard#leaderboard_at_capture'
    get '/get_empty_leaderboard_html' => 'leaderboard#get_empty_leaderboard_html'

    get '/participants/summary/:participant_id' => 'participants#summary'

    scope '/teams' do
      get '/' => 'teams#teams'
      get '/registration' => 'teams#registration'
      post '/registration' => 'teams#registration_create'
      get '/:team_slug' => 'teams#leaderboard'
      get '/:team_slug/confirmation' => 'teams#captain_edit_confirmation', as: 'captain_edit_confirmation_dos'
      get '/:team_slug/:token' => 'teams#captain_edit'
      patch '/:team_slug/:token' => 'teams#captain_edit_commit', as: 'captain_edit'
    end

    scope '/admin' do
      get '/' => 'events#admin'

      scope :reports, as: 'reports' do
        get '/results' => 'event_reports#results'
        get '/categories' => 'event_reports#show_categories'
        get '/team_categories' => 'event_reports#team_categories'
      end

      scope 'sms' do
        get '/' => 'events_sms#index', as: 'sms'
        put '/send_standings' => 'events_sms#send_standings_sms', as: 'sms_send_standings'
        put '/send_custom' => 'events_sms#send_custom_sms', as: 'sms_send_custom'
      end

      resources :captures

      get '/teams/team_lookup', to: 'teams#team_lookup'

      resources :teams do
        member do
          get 'badges', defaults: { format: 'pdf' }
        end

        collection do
          get '/check_badge_status', to: 'teams#check_badge_status'
        end

        get '/check_in' => 'teams#check_in'
        get '/check_out' => 'teams#check_out'
      end

      resources :categories do
        resources :category_items
      end

      resources :super_categories do
        get '/categories' => 'super_categories#categories_index'
      end

      resources :premium_category_groupings

      resources :event_scale_openings

      resources :participants do
        member do
          get 'badge', defaults: { format: 'pdf'}
        end

        get '/get_info', action: :get_info, on: :collection
      end

      resources :participations, except: [:new, :create, :edit, :update, :destroy] do
        get :autocomplete_participation_capture, on: :collection
        get :autocomplete_participation_form, on: :collection
        get '/get_info', action: :get_info, on: :collection
      end

    end
  end
end

app/views/nav/_event_navbar.html.erb
<style type="text/css">
    #big-header {
        margin-top:  45px;
    }
</style>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="<%= event_landing_path(:event_slug => @event.slug) %>">
        <%= @event.icon.nil? ? 'Home' : image_tag(@event.icon.url, class: 'nav-logo') %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if can? :index, Participant %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Participants <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if can? :index, Participant %><li><a href="<%= participants_path(:event_slug => @event.slug) %>">List</a></li><% end %>
                <% if can? :index, Participant %>
                    <li class="divider"></li>
                    <li><a href="<%= participants_path(:event_slug => @event.slug, format: 'xlsx') %>">Download</a></li>
                <% end %>
              </ul>
            </li>
        <% end %>

        <% if (can? :index, Team) || (can? :create, Team) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teams <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if can? :index, Team %><li><a href="<%= teams_path(:event_slug => @event.slug) %>">List</a></li><% end %>
                <% if can? :create, Team %><li><a href="<%= teams_team_lookup_path(:event_slug => @event.slug) %>">New</a></li><% end %>
                <% if can? :index, Team %>
                    <li class="divider"></li>
                    <li><%= link_to 'Download Team Spreadsheet', teams_path(:event_slug => @event.slug, :format => :xlsx), method: :get %></li>
                <% end %>
              </ul>
            </li>
        <% end %>

        <% if (can? :index, EventScaleOpening) || (can? :create, EventScaleOpening) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Scale Openings <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if can? :index, EventScaleOpening %><li><a href="<%= event_scale_openings_path(:event_slug => @event.slug) %>">List</a></li><% end %>
                <% if can? :create, EventScaleOpening %><li><a href="<%= new_event_scale_opening_path(:event_slug => @event.slug) %>">New</a></li><% end %>
              </ul>
            </li>
        <% end %>

        <% if (can? :index, Category) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Scoring <b class="caret"></b></a>
              <ul class="dropdown-menu multi-level">

                <li class="dropdown-submenu">
                  <a tabindex="-1" href="#">Categories</a>
                  <ul class="dropdown-menu">
                    <li><a href="<%= categories_path(:event_slug => @event.slug) %>">List</a></li>
                    <% if can? :create, Category %><li><a href="<%= new_category_path(:event_slug => @event.slug) %>">New</a></li><% end %>
                  </ul>
                </li>

                <li class="dropdown-submenu">
                  <a tabindex="-1" href="#">Super Categories</a>
                  <ul class="dropdown-menu">
                    <li><a href="<%= super_categories_path(:event_slug => @event.slug) %>">List</a></li>
                    <% if can? :create, SuperCategory %><li><a href="<%= new_super_category_path(:event_slug => @event.slug) %>">New</a></li><% end %>
                  </ul>
                </li>

                <li class="dropdown-submenu">
                  <a tabindex="-1" href="#">Premium Category Groupings</a>
                  <ul class="dropdown-menu">
                    <li><a href="<%= premium_category_groupings_path(:event_slug => @event.slug) %>">List</a></li>
                    <% if can? :create, PremiumCategoryGrouping %><li><a href="<%= new_premium_category_grouping_path(:event_slug => @event.slug) %>">New</a></li><% end %>
                  </ul>
                </li>

                <li class="divider"></li>
                <li><a href="<%= reports_categories_path(:event_slug => @event.slug) %>">Summary</a></li>
              </ul>
            </li>
        <% end %>

        <% if (can? :index, Capture) || (can? :create, Capture) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Captures <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if can? :index, Capture %><li><a href="<%= captures_path(:event_slug => @event.slug, :page => 1) %>">List</a></li><% end %>
                <% if can? :create, Capture %><li><a href="<%= new_capture_path(:event_slug => @event.slug) %>">New</a></li><% end %>
                <% if can? :index, Capture %>
                    <li class="divider"></li>
                    <li><a href="<%= captures_path(:event_slug => @event.slug, format: 'xlsx') %>">Download</a></li>
                <% end %>
              </ul>
            </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<%= leaderboard_path(:event_slug => @event.slug) %>">Leaderboard</a></li>
            <li><a href="<%= "/#{@event.slug.html_safe}/teams" %>">Team List</a></li>
            <li><a href="<%= facts_path(:event_slug => @event.slug) %>">Facts Page</a></li>
            <% if can? :show, @event %><li><a href="<%= reports_team_categories_path(@event.slug) %>">Team Categories</a></li><% end %>
            <% if can? :show, @event %><li><a href="<%= reports_results_path(:event_slug => @event.slug) %>">Printable Results</a></li><% end %>
            <% if can? :send_sms_messages, @event %><li><a href="<%= sms_path(event_slug: @event.slug) %>">Send SMS Reports</a></li><% end %>
          </ul>
        </li>

        <% if can? :index, Event %>
            <li><%= link_to 'Admin', '/admin' %></li>
        <% end %>
      </ul>

      <p class="navbar-text pull-right nav-event-title" style="display: none"><%= @event.nil? ? 'Geaux Fish Louisiana Rodeos' : @event.name  %></p>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.decorated_name(@event) %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li style="border-left:1px solid #c0c0c0;"><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/nav/_nav.html.erb
<div class="wrapper text-center">

  <!-- BEGIN Dark navigation bar -->
  <nav class="dark">
    <ul class="clear">
      <li><a data-load="<%= admin_path(:event_slug => @event.slug)%>">Home</a></li>

      <li><a data-load="<%= participants_path(:event_slug => @event.slug) %>">Participants</a>
        <ul>
          <li><a data-load="<%= new_participant_path(:event_slug => @event.slug) %>">New</a></li>
        </ul>
      </li>

      <li><a data-load="<%= teams_path(:event_slug => @event.slug) %>">Teams</a>
        <ul>
          <li><a data-load="<%= new_team_path(:event_slug => @event.slug) %>">New</a></li>
          <li><form method="get" action="<%= teams_path(:event_slug => @event.slug, :format => :xlsx) %>">
            <button type="submit">Team Edit SpreadSheet</button>
          </form></li>
        </ul>
      </li>

      </li>
      <li><a data-load="<%= captures_path(:event_slug => @event.slug) %>">Captures</a>
        <ul>
          <li><a data-load="<%= new_capture_path(:event_slug => @event.slug) %>">New</a></li>
        </ul>
      </li>

    </ul>
  </nav>
  <!-- END Dark navigation bar -->
</div>

app/views/nav/_tracking.html.erb
<% if Rails.env == 'production'%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42399566-1', 'geauxfishlarodeo.com');
    ga('send', 'pageview');

  </script>
<% end %>